version: '3'

services:

  frontend:
    build: ./frontend
    restart: always
    command: npm run dev
    volumes:
      - ./frontend:/vue_app
    ports:
      - "3000:5000"
    expose:
      - "3000"